// sub-react/src/views/home/home.js
import { Component } from "react";
import { connect } from "react-redux";
import { Button, Card } from "antd";

const mapStateToProps = (state) => {
  return {
    userInfo: state.globalData.userInfo,
  };
};

const mapDispatchProps = (dispatch) => {
  return {
    SET_USER_INFO: function (data) {
      dispatch({ type: "SET_GLOBAL_DATA", data });
    },
  };
};

class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div>
        <h1>子Sub-React应用</h1>
        <Card title='技术栈' style={{ width: "90%", margin: "0 auto", marginTop: "20px" }}>
          <p>前端底层框架：React[17.0.1]</p>
          <p>前端UI框架：antd[4.9.4]</p>
          <p>状态管理工具：react-redux[7.2.2]</p>
          <p>路由管理：react-router-dom[5.2.0]</p>
        </Card>
        <Card title='测试区域' style={{ width: "90%", margin: "0 auto", marginTop: "20px" }}>
          <p>
            测试数据通信：
            <span>当前模块获取数据：{JSON.stringify(this.props.userInfo)}</span>
            <Button type='primary' onClick={() => this.changeUserInfo()}>
              变更数据
            </Button>
          </p>
          <p>
            测试当前应用路由管理：{" "}
            <Button type='primary' onClick={() => this.goToAboutPage()}>
              跳转到About页面
            </Button>
          </p>
          <p>
            测试子应用互相跳转：{" "}
            <Button type='primary' onClick={() => this.goToSubVueApp()}>
              跳转到子Sub-vue应用
            </Button>
          </p>
        </Card>
      </div>
    );
  }
  changeUserInfo() {
    this.props.SET_USER_INFO({ userInfo: { name: "sub-react" } });
  }

  goToAboutPage() {
    this.props.history.push("/about");
  }

  goToSubVueApp() {
    window.location.href = "/vue";
  }
}

const HomeRedux = connect(mapStateToProps, mapDispatchProps)(Home);
export default HomeRedux;

// sub-angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import {Router} from '@angular/router';
import {Observable} from 'rxjs';

import { Subscription } from 'rxjs';
import {
  singleSpaPropsSubject,
} from 'src/single-spa/single-spa-props';

@Component({
  selector: 'sub-angular-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.less']
})
export class HomeComponent implements OnInit {
  globalData$:Observable<object>;
  subscription: Subscription; 
  userInfo= {};
  qkProps:{setGlobalState?:any,getGlobalState?:any };

  constructor(private router:Router) {}

  ngOnInit(): void {
    this.subscription = singleSpaPropsSubject.subscribe(
      props => {
        this.qkProps = props;
        let globalData = props.getGlobalState();
        if(globalData.userInfo && Object.keys(globalData.userInfo).length>0){
          this.userInfo = globalData.userInfo
        }
      },
    );
  }

 ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }


  changeUserInfo(){
      this.userInfo = { name: "sub-angular"};
      this.qkProps.setGlobalState({ userInfo: { name: "sub-angular" } });
  }

  goToAboutPage():void{
    this.router.navigate(["about"])
  }

  goToSubReactApp():void{
    window.location.href = "/react"
  }
  printData():void{}
}

<h1 nz-typography>Sub-Angular应用</h1>

<nz-card style="width: 90%; margin: 0 auto; margin-top: 20px" nzTitle="技术栈">
  <p>前端底层框架：angular[9.1.13]</p>
  <p>前端UI框架：ng-zorro-antd[9.3.0]</p>
  <p>路由管理：@angular/router[9.1.13]</p>
  <p>
    微前端框架：single-spa[5.8.3]
    <nz-divider nzType="vertical"></nz-divider>single-spa-angular[4.9.1]
  </p>
</nz-card>
<nz-card
  style="width: 90%; margin: 0 auto; margin-top: 20px"
  nzTitle="测试区域"
>
  <p>
    测试数据通信：
    <span>当前模块获取数据：{{ userInfo | toJsonStr }}</span>
    <button nz-button nzType="primary" (click)="changeUserInfo()">
      变更数据
    </button>
  </p>
  <p>
    测试当前应用路由管理：
    <button nz-button nzType="primary" (click)="goToAboutPage()">
      跳转到about页面
    </button>
  </p>
  <p>
    测试子应用互相跳转：<button
      nz-button
      nzType="primary"
      (click)="goToSubReactApp()"
    >
      跳转到子react应用
    </button>
  </p>
</nz-card>
